name: Deploy to Godaddy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy to Godaddy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Staging site if branch is dev
        if: github.ref == 'refs/heads/dev'
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_DEV }}:/home/uenlppo34djc/public_html/

      - name: Deploy to Godaddy via SFTP
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/uenlppo34djc/public_html/
